name: "Epever solar client"
description: "Epever solar client"
version: "1.2.11"
slug: "epever-solar-client"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  server:
    - name: epever
      host: 192.168.88.78
      port: 9999
  mqtt:
    host: 'homeassistant.local'
    port: 1883
    username: 'mqtt'
    password: 'mqtt'
    topic: home/epever-solar
    debug: false
schema:
  server:
    - name: str
      host: str
      port: int(0,65535)
  mqtt:
    host: str
    port: int(0,65535)
    username: str
    password: password
    topic: str
    debug: bool
